### ISSUE TITLE
SATA not working after latest changes

### ISSUE THREAD

**Issue by b-man** [MarvellEmbeddedProcessors/edk2-open-platform#3]
Hello,

After rebuilding edk2 against the latest changes in this repo and flashing it to my board
STAT no longer appears to be working. All of the other devices (e/MMC, PXE, USB) show
up in the Boot Manager, but my SATA SSD no longer appears.

Currently visible devices dumped using map:

`Mapping table
      FS0: Alias(s):HD1b0b:;BLK1:
          VenHw(0D51905B-B77E-452A-A2C0-ECA0CC8D514A,000051F20000000000)/USB(0x1
,0x0)/HD(1,MBR,0x00000000,0x20,0xEE8BE0)
      FS1: Alias(s):F0:;BLK5:
          VenMsg(06ED4DD0-FF78-11D3-BDC4-00A0C94053D1,0200000000000000)
     BLK0: Alias(s):
          VenHw(0D51905B-B77E-452A-A2C0-ECA0CC8D514A,000051F20000000000)/USB(0x1
,0x0)
     BLK2: Alias(s):
          VenHw(0D51905B-B77E-452A-A2C0-ECA0CC8D514A,00006EF00000000000)/eMMC(0x
0)/Ctrl(0x0)
     BLK3: Alias(s):
          VenHw(0D51905B-B77E-452A-A2C0-ECA0CC8D514A,00006EF00000000000)/eMMC(0x
0)/Ctrl(0x1)
     BLK4: Alias(s):
          VenHw(0D51905B-B77E-452A-A2C0-ECA0CC8D514A,00006EF00000000000)/eMMC(0x
0)/Ctrl(0x2)
`

I've rebuilt the firmware following the official guide, with the exception of using the UDK2018 branch of edk2 as recent changes in the main branch breaks the MvSpiDxe driver ([this change](https://github.com/tianocore/edk2/commit/6281a2ed3bb3ffe57ed54cabd9a31dcf13b415f8) breaks the build, and applying the changes made in NorFlashFvbDxe to MvSpiDxe results in a runtime error at boot).

**Comment by wojtas-marcin** [comment]
Hi!

I tested branch with edk2 from April 10th, wasn't aware of the regression:/ - noticed it today when working on edk2-platforms. About SATA missing - I need to withdraw a commit that relies on newer ATF than available publicly. I'll work on both today and update. Sorry for inconvenience.

Best regards,
Marcin

**Comment by wojtas-marcin** [comment]
I updated marvell-armada-wip to resolve newest mainline EDK2 dependencies and removed dependency on not-yet-published ATF code. Please verify and let know, if we can close this one.

**Comment by b-man** [comment]
I can confirm that these changes did resolve the issue and I can now boot off of my SSD. Thank you for the quick response!

Best regards,
Brian
