### ISSUE TITLE
RTC read/update is unreliable

### ISSUE THREAD

**Issue by kettenis** [MarvellEmbeddedProcessors/edk2-open-platform#8]
On my MACCHIATObin (single-shot) reading and/or updating the RTC is unreliable. Sometimes the date is completely off. Changing the bus parameters to match what
mainline Linux does makes things work for me.

**Comment by wojtas-marcin** [comment]
Fix merged:
https://github.com/MarvellEmbeddedProcessors/edk2-open-platform/commit/f1d266b838420e248281afbbb9c5abc6d640f63b

Thanks!
